<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ServicioPaqueteriaWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/ServicioPaqueteriaWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/ServicioPaqueteriaWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://wsPaqueteria/">
    <import location="http://148.205.38.104:8080/ServicioPaqueteria/ServicioPaqueteria?WSDL" namespace="http://wsPaqueteria/"/>
    <plnk:partnerLinkType name="ServicioPaqueteriaLinkType">
        <plnk:role name="ServicioPaqueteriaRole" portType="ns:ServicioPaqueteria"/>
    </plnk:partnerLinkType>
</definitions>
